name: deploy
on:
  release:
    types: [published]
jobs:
  build:
      permissions:
        contents: read
        pull-requests: write
        id-token: write  # Required for NPM Publish OIDC
      uses: web-illinois/toolkit-management/.github/workflows/component_deploy.yml@main
      with:
        COMPONENT_NAME: ${{github.event.repository.name}}
      secrets:
        TOOLKIT_AWS_ACCESS_SECRET: ${{ secrets.TOOLKIT_AWS_ACCESS_SECRET }}
